stages:

  update_biobricks_dependencies:
    cmd: stages/00_update_biobricks_deps.sh
    deps:
      - stages/00_update_biobricks_deps.sh

  process-annotations:
    cmd: stages/01_process.py
    deps:
      - .bb/dependencies.txt
      - stages/01_process.py
      - stages/physchem_terms.json
    outs:
      - brick/pubchem-annotations-physchem.nt
